# Generated by Django 5.0.2 on 2024-03-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('en', 'English'), ('ma', 'Maths'), ('hi', 'History')], default=1, max_length=50),
        ),
    ]
