# Generated by Django 5.0.2 on 2024-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('fd', 'FrontEnd Development'), ('bd', 'Backend Development')], default=1, max_length=50),
        ),
    ]
