# Generated by Django 5.0.2 on 2024-04-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_author_remove_article_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
