# Generated by Django 5.0.2 on 2024-04-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
