# Generated by Django 5.0.2 on 2024-04-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
