# Generated by Django 5.0.2 on 2024-04-08 02:33

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_article_date_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=None, null=True),
        ),
    ]
